// <auto-generated />
using System;
using Infrastrucure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastrucure.Migrations
{
    [DbContext(typeof(TenderContext))]
    [Migration("20251209121036_create_DB_for_tenderSide")]
    partial class create_DB_for_tenderSide
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entity.Tender", b =>
                {
                    b.Property<int>("tenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tenderId"));

                    b.Property<DateOnly>("closingDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("issueDate")
                        .HasColumnType("date");

                    b.Property<int>("tenderCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("tenderDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenderTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tenderTypeId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("tenderId");

                    b.HasIndex("tenderCategoryId")
                        .IsUnique();

                    b.HasIndex("tenderTypeId")
                        .IsUnique();

                    b.HasIndex("userId");

                    b.ToTable("tenders");
                });

            modelBuilder.Entity("Domain.Entity.TenderCategory", b =>
                {
                    b.Property<int>("tenderCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tenderCategoryId"));

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tenderCategoryId");

                    b.ToTable("tenderCategories");
                });

            modelBuilder.Entity("Domain.Entity.TenderDocument", b =>
                {
                    b.Property<int>("tenderDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tenderDocumentId"));

                    b.Property<string>("addBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("documentPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tenderId")
                        .HasColumnType("int");

                    b.HasKey("tenderDocumentId");

                    b.HasIndex("tenderId");

                    b.ToTable("tenderDocuments");
                });

            modelBuilder.Entity("Domain.Entity.TenderType", b =>
                {
                    b.Property<int>("tenderTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tenderTypeId"));

                    b.Property<string>("typeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tenderTypeId");

                    b.ToTable("tenderTypes");
                });

            modelBuilder.Entity("Domain.Entity.Users", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entity.Tender", b =>
                {
                    b.HasOne("Domain.Entity.TenderCategory", "tenderCategory")
                        .WithOne("tender")
                        .HasForeignKey("Domain.Entity.Tender", "tenderCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.TenderType", "tenderType")
                        .WithOne("tender")
                        .HasForeignKey("Domain.Entity.Tender", "tenderTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.Users", "user")
                        .WithMany("tenders")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tenderCategory");

                    b.Navigation("tenderType");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Domain.Entity.TenderDocument", b =>
                {
                    b.HasOne("Domain.Entity.Tender", "tender")
                        .WithMany("tenderDocuments")
                        .HasForeignKey("tenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tender");
                });

            modelBuilder.Entity("Domain.Entity.Tender", b =>
                {
                    b.Navigation("tenderDocuments");
                });

            modelBuilder.Entity("Domain.Entity.TenderCategory", b =>
                {
                    b.Navigation("tender")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entity.TenderType", b =>
                {
                    b.Navigation("tender")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entity.Users", b =>
                {
                    b.Navigation("tenders");
                });
#pragma warning restore 612, 618
        }
    }
}
