// <auto-generated />
using System;
using Infrastrucure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastrucure.Migrations
{
    [DbContext(typeof(TenderContext))]
    [Migration("20260101191438_add_indexes")]
    partial class add_indexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entity.Bids.Bid", b =>
                {
                    b.Property<int>("bidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bidId"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("paymentTermsId")
                        .HasColumnType("int");

                    b.Property<int>("tenderId")
                        .HasColumnType("int");

                    b.Property<decimal>("totalBidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("bidId");

                    b.HasIndex("paymentTermsId")
                        .IsUnique();

                    b.HasIndex("tenderId");

                    b.HasIndex("userId");

                    b.ToTable("bids");
                });

            modelBuilder.Entity("Domain.Entity.Bids.BidDocument", b =>
                {
                    b.Property<int>("bidDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bidDocumentId"));

                    b.Property<int>("bidId")
                        .HasColumnType("int");

                    b.Property<string>("companyRegistrationCertificate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("financialStatementsLast_2Years")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("taxComplianceCertificate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("technicalProposalId")
                        .HasColumnType("int");

                    b.HasKey("bidDocumentId");

                    b.HasIndex("bidId")
                        .IsUnique();

                    b.HasIndex("technicalProposalId")
                        .IsUnique();

                    b.ToTable("bidDocuments");
                });

            modelBuilder.Entity("Domain.Entity.Bids.Declaretion", b =>
                {
                    b.Property<int>("declaretionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("declaretionId"));

                    b.Property<int>("bidId")
                        .HasColumnType("int");

                    b.Property<string>("declarationText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("declaretionId");

                    b.HasIndex("bidId")
                        .IsUnique();

                    b.ToTable("declaretions");
                });

            modelBuilder.Entity("Domain.Entity.Bids.FinancialProposal", b =>
                {
                    b.Property<int>("financialProposalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("financialProposalId"));

                    b.Property<int>("bidDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("itemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("totalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("unitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("financialProposalId");

                    b.HasIndex("bidDocumentId");

                    b.ToTable("financialProposals");
                });

            modelBuilder.Entity("Domain.Entity.Bids.PaymentTerms", b =>
                {
                    b.Property<int>("paymentTermsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("paymentTermsId"));

                    b.Property<string>("PaymentScheduleAdvance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentScheduleAdvanceFinalApproval")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentScheduleUponMilestoneCompletion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PenaltiesForDelays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("termMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("paymentTermsId");

                    b.ToTable("paymentTerms");
                });

            modelBuilder.Entity("Domain.Entity.Bids.TechnicalProposal", b =>
                {
                    b.Property<int>("TechnicalProposalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TechnicalProposalId"));

                    b.Property<string>("methodologyDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("proposedSolution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("technicalApproachDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TechnicalProposalId");

                    b.ToTable("technicalProposals");
                });

            modelBuilder.Entity("Domain.Entity.EligibilityCriteria", b =>
                {
                    b.Property<int>("EligibilityCriteriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EligibilityCriteriaId"));

                    b.Property<string>("CriteriaDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tenderId")
                        .HasColumnType("int");

                    b.HasKey("EligibilityCriteriaId");

                    b.HasIndex("tenderId");

                    b.ToTable("EligibilityCriterias");
                });

            modelBuilder.Entity("Domain.Entity.Evaluation.WinBid", b =>
                {
                    b.Property<int>("winBidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("winBidId"));

                    b.Property<DateOnly>("awardedDate")
                        .HasColumnType("date");

                    b.Property<int>("bidId")
                        .HasColumnType("int");

                    b.Property<string>("comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tenderId")
                        .HasColumnType("int");

                    b.HasKey("winBidId");

                    b.HasIndex("bidId")
                        .IsUnique();

                    b.HasIndex("tenderId")
                        .IsUnique();

                    b.ToTable("winBids");
                });

            modelBuilder.Entity("Domain.Entity.Roles", b =>
                {
                    b.Property<int>("roleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("roleId"));

                    b.Property<string>("roleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("roleId");

                    b.HasIndex("roleName")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Domain.Entity.Tender", b =>
                {
                    b.Property<int>("tenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tenderId"));

                    b.Property<double>("budget")
                        .HasColumnType("float");

                    b.Property<DateOnly>("closingDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("issueDate")
                        .HasColumnType("date");

                    b.Property<int>("tenderCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("tenderDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenderTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tenderTypeId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("tenderId");

                    b.HasIndex("tenderCategoryId");

                    b.HasIndex("tenderTypeId");

                    b.HasIndex("userId");

                    b.ToTable("tenders");
                });

            modelBuilder.Entity("Domain.Entity.TenderCategory", b =>
                {
                    b.Property<int>("tenderCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tenderCategoryId"));

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("tenderCategoryId");

                    b.HasIndex("categoryName")
                        .IsUnique();

                    b.ToTable("tenderCategories");
                });

            modelBuilder.Entity("Domain.Entity.TenderDocument", b =>
                {
                    b.Property<int>("tenderDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tenderDocumentId"));

                    b.Property<string>("addBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("documentPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tenderId")
                        .HasColumnType("int");

                    b.HasKey("tenderDocumentId");

                    b.HasIndex("tenderId");

                    b.ToTable("tenderDocuments");
                });

            modelBuilder.Entity("Domain.Entity.TenderType", b =>
                {
                    b.Property<int>("tenderTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tenderTypeId"));

                    b.Property<string>("typeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("tenderTypeId");

                    b.HasIndex("typeName")
                        .IsUnique();

                    b.ToTable("tenderTypes");
                });

            modelBuilder.Entity("Domain.Entity.UserRoles", b =>
                {
                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<int>("roleId")
                        .HasColumnType("int");

                    b.HasKey("userId", "roleId");

                    b.HasIndex("roleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Domain.Entity.Users", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entity.Bids.Bid", b =>
                {
                    b.HasOne("Domain.Entity.Bids.PaymentTerms", "paymentTerms")
                        .WithOne("bid")
                        .HasForeignKey("Domain.Entity.Bids.Bid", "paymentTermsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entity.Tender", "tender")
                        .WithMany("bids")
                        .HasForeignKey("tenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entity.Users", "user")
                        .WithMany("bids")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("paymentTerms");

                    b.Navigation("tender");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Domain.Entity.Bids.BidDocument", b =>
                {
                    b.HasOne("Domain.Entity.Bids.Bid", "bid")
                        .WithOne("bidDocument")
                        .HasForeignKey("Domain.Entity.Bids.BidDocument", "bidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.Bids.TechnicalProposal", "technicalProposal")
                        .WithOne("bidDocument")
                        .HasForeignKey("Domain.Entity.Bids.BidDocument", "technicalProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bid");

                    b.Navigation("technicalProposal");
                });

            modelBuilder.Entity("Domain.Entity.Bids.Declaretion", b =>
                {
                    b.HasOne("Domain.Entity.Bids.Bid", "bid")
                        .WithOne("declaretion")
                        .HasForeignKey("Domain.Entity.Bids.Declaretion", "bidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bid");
                });

            modelBuilder.Entity("Domain.Entity.Bids.FinancialProposal", b =>
                {
                    b.HasOne("Domain.Entity.Bids.BidDocument", "bidDocument")
                        .WithMany("financialProposal")
                        .HasForeignKey("bidDocumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("bidDocument");
                });

            modelBuilder.Entity("Domain.Entity.EligibilityCriteria", b =>
                {
                    b.HasOne("Domain.Entity.Tender", "tender")
                        .WithMany("eligibilityCriterias")
                        .HasForeignKey("tenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tender");
                });

            modelBuilder.Entity("Domain.Entity.Evaluation.WinBid", b =>
                {
                    b.HasOne("Domain.Entity.Bids.Bid", "bid")
                        .WithOne("winBid")
                        .HasForeignKey("Domain.Entity.Evaluation.WinBid", "bidId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entity.Tender", "tender")
                        .WithOne("winBid")
                        .HasForeignKey("Domain.Entity.Evaluation.WinBid", "tenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("bid");

                    b.Navigation("tender");
                });

            modelBuilder.Entity("Domain.Entity.Tender", b =>
                {
                    b.HasOne("Domain.Entity.TenderCategory", "tenderCategory")
                        .WithMany("tender")
                        .HasForeignKey("tenderCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.TenderType", "tenderType")
                        .WithMany("tender")
                        .HasForeignKey("tenderTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.Users", "user")
                        .WithMany("tenders")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tenderCategory");

                    b.Navigation("tenderType");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Domain.Entity.TenderDocument", b =>
                {
                    b.HasOne("Domain.Entity.Tender", "tender")
                        .WithMany("tenderDocuments")
                        .HasForeignKey("tenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tender");
                });

            modelBuilder.Entity("Domain.Entity.UserRoles", b =>
                {
                    b.HasOne("Domain.Entity.Roles", "role")
                        .WithMany("userRoles")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.Users", "user")
                        .WithMany("userRoles")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Domain.Entity.Bids.Bid", b =>
                {
                    b.Navigation("bidDocument")
                        .IsRequired();

                    b.Navigation("declaretion")
                        .IsRequired();

                    b.Navigation("winBid")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entity.Bids.BidDocument", b =>
                {
                    b.Navigation("financialProposal");
                });

            modelBuilder.Entity("Domain.Entity.Bids.PaymentTerms", b =>
                {
                    b.Navigation("bid")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entity.Bids.TechnicalProposal", b =>
                {
                    b.Navigation("bidDocument")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entity.Roles", b =>
                {
                    b.Navigation("userRoles");
                });

            modelBuilder.Entity("Domain.Entity.Tender", b =>
                {
                    b.Navigation("bids");

                    b.Navigation("eligibilityCriterias");

                    b.Navigation("tenderDocuments");

                    b.Navigation("winBid")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entity.TenderCategory", b =>
                {
                    b.Navigation("tender");
                });

            modelBuilder.Entity("Domain.Entity.TenderType", b =>
                {
                    b.Navigation("tender");
                });

            modelBuilder.Entity("Domain.Entity.Users", b =>
                {
                    b.Navigation("bids");

                    b.Navigation("tenders");

                    b.Navigation("userRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
